### ISSUE TITLE
Update strategy for a SHOGun2-based web application

### ISSUE THREAD

**Issue by chrismayer** [terrestris/shogun2#119]
Hi,

is there an update strategy for an existing SHOGun2-based web application? Due to the changes in the last 2 days (v0.0.3-SNAPSHOT)  I updated the base SHOGun2-artifacts and run 

`` $ mvn clean install``
`` $ mvn eclipse:clean eclipse:eclipse``

on the ``src`` folder.
After that my existing web applications had some errors (which is reasonable due to code changes in the base artifacts). But is there a smooth way to solve them? Or how do you solve this problem?

Thanks for any hint!

**Comment by buehner** [comment]
You can try to set the `shogun2.version` property in the `pom.xml` of your project to the current SHOGun version (e.g. `0.0.3-SNAPSHOT`).

But i suggest that this will not solve all problems because there were some major changes (e.g. #114 ) in the last commits.

I think we cannot fully avoid that these kind of problems will occur in the current state of the project as there is a lot of developing going on.

What you can always do is: Use the latest webapp-archetype to create a compatible webapp (and possibly migrate things from your existing project). :smile:

**Comment by buehner** [comment]
One more thing: As i mentioned in #117 i would highly recommend to not use `mvn eclipse:eclipse` anymore, but the Eclipse m2e plugin instead. This has a lot advantages (e.g. Resolving of dependencies in the eclipse workspace).

To do this, you simply have to checkout SHOGun2 and use the `File -> Import -> Existing Maven Projects` in eclipse (by pointing to the shogun2 root folder).

I suggest to use the m2e plugin with version 1.6 or higher (as 1.5. might not be fully compatible to our maven multi module project)

**Comment by chrismayer** [comment]
Hi @buehner,

thanks for your quick reply. That is what I expected. I just wanted to be sure that I am not missing any magic script :dizzy: which solves this :wink: .
I think I go the way of generating a new web project and try to port my changes.

Thanks as well for the hint with the m2e. I'll give it a shot.

Think we can close this, or?

**Comment by marcjansen** [comment]
You could try to document the changes you need to do and add them to the release notes?!? If you have the time, that is.

**Comment by buehner** [comment]
I'll close this issue now. Just open a new one if there are more questions.
